
App:
  name: "default"
  version: "1.0.0"
  description: "This is XXX1 application"
  port: 8000
  host: "localhost"
  env: "dev"


Logger:
  common:
    sh_level: DEBUG
    sh_format: "<green>{time: YYYY-MM-DD HH:mm:ss}</green> | <level>{level: <8}</level> | <cyan>{name}:{function}:{line}</cyan> | <level>{message}</level>"
    sh_colorize: true
    fh_level: "DEBUG"
    fh_format: "{time:YYYY-MM-DD HH:mm:ss:SSS} | {level: <8} | {process}:{thread} | {name}:{function}:{line} | {message}"
    fh_rotation: "10 MB"
    fh_retention: "1 weeks"
    fh_compression: "zip"
    fh_serialize: false
    fh_encoding: "utf-8"
    fh_enqueue: true
    fh_diagnose: true
    sensitive_fields: (password|token|key|secret|token|session|cookie|csrf|jwt|access_token|refresh_token|id_token|client_secret|client_id|api_key|secret_key)
    sensitive_fields_replacement: "********"
    max_length: 1000
    max_length_replacement: "..."
  console:
    sh_level: "DEBUG"
  run:
    fh_level: "INFO"
    fh_sink: F:\Code\A-Practice\base\base-backend\output\logs\default\run.log
  operate:
    fh_level: "INFO"
    fh_sink: F:\Code\A-Practice\base\base-backend\output\logs\default\operate.log
  api:
    fh_level: "INFO"
    fh_sink: F:\Code\A-Practice\base\base-backend\output\logs\default\api.log
  agent:
    fh_level: "DEBUG"
    fh_sink: F:\Code\A-Practice\base\base-backend\output\logs\default\agent.log


DB:
  url: "mysql+pymysql://root:123456@localhost:3306/base-backend"

Celery:
  run: true
  broker: "redis://localhost:6379/0"
  backend: "db+mysql+pymysql://root:123456@localhost:3306/base-backend"
  worker:
    logfile: F:\Code\A-Practice\base\base-backend\output\logs\app_xxx1\celery_worker.log
    loglevel: DEBUG
    pool: threads
    concurrency: 4
  
  beat:
    logfile: F:\Code\A-Practice\base\base-backend\output\logs\app_xxx1\celery_beat.log
    loglevel: DEBUG

Connectors:
  HttpRequest:
    file_max_size: 20971520

    
  conections:
    
    SshConnection:
      timeout: 10
      banner_timeout: 60

Services:
  Py4jdbcAgentServer:
    mysql:
      host: "localhost"
      port: 38801
      url: jdbc:mysql://
      driver: "com.mysql.cj.jdbc.Driver"
      jar: "mysql-connector-j-8.3.0.jar"
      run: true
    gauss:
      host: "localhost"
      port: 38802
      url: jdbc:gaussdb://
      driver: "com.huawei.gauss.jdbc.GaussDriver"
      jar: "gaussdb-jdbc-2.8.0.jar"
      run: false
